app/assets/javascripts/components/measure_form.js
app/views/measures/measures/_form.html.slim

Tested precompiling assets, everything works...
Putting these fixes back after deployment failures earlier today.

Measure form improvements

---

app/controllers/measures/measures_controller.rb
app/controllers/measures/monetary_units_controller.rb
app/interactors/measure_saver.rb
app/models/footnote.rb
app/models/monetary_unit.rb
config/routes.rb

*THIS PR COVERS:*
- Added saving of Quotas
- Added saving of Footnotes

[WIP] Saving measures

---

app/assets/javascripts/components/measure_form.js
app/assets/stylesheets/components/forms.scss
app/assets/stylesheets/simple-grid.scss
app/views/measures/measures/_form.html.slim
app/views/measures/measures/form_parts/_conditions.html.slim
app/views/measures/measures/form_parts/_duty_expression.html.slim
app/views/measures/measures/form_parts/_footnotes.html.slim
app/views/measures/measures/form_parts/_operation_date.html.slim
app/views/measures/measures/form_parts/_quota.html.slim
app/views/shared/vue_templates/_condition.html.slim
app/views/shared/vue_templates/_date_select.html.slim
app/views/shared/vue_templates/_measure_origin.html.slim

This PR does the following:
- Operation date field
- Remove footnotes
- Remove conditions
- Remove duty expressions
- Remove quota period
- Change date field to datepicker

More UI tweaks

---

app/assets/javascripts/components/measure_form.js
app/controllers/xml_generation/exports_controller.rb
app/interactors/measure_saver.rb
app/views/measures/measures/form_parts/_quota.html.slim
app/views/shared/vue_templates/_quota_period.html.slim

1) Measure form JS: fixed issues with duty expression rendering for conditions 
2) Quota definition: saving bugfixes
3) Added saving of data from 'Specify conditions' section
4) Order number: saving of origins and excluded areas

[MEASURE SAVER] updates

---

app/assets/javascripts/components/measure_form.js
app/assets/javascripts/vendors/selectize.js
app/assets/stylesheets/application.scss
app/assets/stylesheets/components/select.scss
app/assets/stylesheets/vendors/selectize.bootstrap3.scss
app/views/shared/vue_templates/_condition.html.slim

Forked library to be able to add these clear selection "x"s.
Added to ALL dropdowns.

Adding forked version of lib to be able to implement clear selection feature

---

.gitignore
config/initializers/shrine.rb

1) [SHRINE S3] make sure we always using private S3 settings
2) [.gitignore] added CF server related folders

[SHRINE AWS S3 FILE UPLOADS] make sure we always using private access mode

---

.circleci/config.yml

[TRELLO CARD](https://trello.com/c/DH6arlxx/168-setup-a-new-env-management-dev-so-that-the-current-env-can-be-used-for-demos-etc)

[CIRCLE CI] auto-deploy to beta server if PR merged into the 'staging' branch

---

app/views/xml_generation/templates/regulations/base_regulation.builder
app/views/xml_generation/templates/regulations/complete_abrogation_regulation.builder
app/views/xml_generation/templates/regulations/explicit_abrogation_regulation.builder
app/views/xml_generation/templates/regulations/full_temporary_stop_regulation.builder
app/views/xml_generation/templates/regulations/modification_regulation.builder
app/views/xml_generation/templates/regulations/prorogation_regulation.builder

[Related sentry issue](https://sentry.io/bit-zesty-client-apps/management/issues/531936791)

[XML Export] issue with exporting of ModificationRegulation undefined method `strftime'

---

app/interactors/regulation_saver.rb
spec/support/shared_contexts/form_savers/abrogation_regulation_general_context.rb
spec/support/shared_contexts/form_savers/regulation_saver_base_context.rb
spec/unit/form_savers/regulation_saver/base_regulation_spec.rb
spec/unit/form_savers/regulation_saver/complete_abrogation_spec.rb
spec/unit/form_savers/regulation_saver/definitive_anti_dumping_countervailing_duty_spec.rb
spec/unit/form_savers/regulation_saver/explicit_abrogation_regulation_spec.rb
spec/unit/form_savers/regulation_saver/full_temporary_stop_regulation_spec.rb
spec/unit/form_savers/regulation_saver/modification_regulation_spec.rb
spec/unit/form_savers/regulation_saver/prorogation_regulation_spec.rb
spec/unit/form_savers/regulation_saver/provisional_anti_dumping_countervailing_duty_regulation_spec.rb
spec/unit/form_savers/regulation_saver_spec.rb

[TRELLO CARD](https://trello.com/c/EbZmbJYu/158-create-regulation-phase-1)

[REGULATIONS SAVER] added unit Rspec tests

---

app/controllers/regulation_form_api/regulation_groups_controller.rb
app/models/regulation_group.rb
spec/requests/form_apis/regulations/regulation_groups_spec.rb
spec/requests/form_apis/regulations/regulations_spec.rb
spec/support/shared_contexts/form_apis/base_context.rb

[TRELLO CARD](https://trello.com/c/EbZmbJYu/158-create-regulation-phase-1)

[RSPEC TESTS] added for Regulation Form APIs

---

app/controllers/additional_codes/additional_codes_controller.rb
app/controllers/footnotes/footnote_types_controller.rb
app/controllers/footnotes/footnotes_controller.rb
app/controllers/measures/measure_type_series_controller.rb
app/controllers/measures/measure_types_controller.rb
app/models/additional_code.rb
app/models/footnote.rb
app/models/footnote_type.rb
app/models/measure_type.rb
app/models/measure_type_series.rb
spec/requests/form_apis/measures/additional_codes_spec.rb
spec/requests/form_apis/measures/footnote_types_spec.rb
spec/requests/form_apis/measures/footnotes_spec.rb
spec/requests/form_apis/measures/measure_type_series_spec.rb
spec/requests/form_apis/measures/measure_types_spec.rb
spec/requests/form_apis/measures/quota_order_numbers_spec.rb
spec/requests/form_apis/measures/regulations_spec.rb
spec/requests/form_apis/regulations/regulations_spec.rb
spec/support/shared_contexts/form_apis/base_context.rb
spec/support/shared_contexts/form_apis/regulations_context.rb

[TRELLO CARD](https://trello.com/c/fB2ulVCR/151-refactor-code-and-write-automated-tests-18)

[Measures] unit tests + form api endpoints improvements

---

.circleci/config.yml
Gemfile
Gemfile.lock
README.md
app/interactors/measure_saver.rb
bin/circle
db/migrate/20180505084755_add_added_at_and_added_by_id_to_footnotes.rb
db/migrate/20180505091501_add_added_at_and_added_by_to_footnote_association_measures.rb
db/migrate/20180505092846_add_added_at_and_added_by_id_to_footnote_descriptions.rb
db/structure.sql
spec/rails_helper.rb
spec/support/shared_contexts/form_savers/measure_saver_base_context.rb
spec/unit/form_savers/measure_saver/duty_expression_spec.rb
spec/unit/form_savers/measure_saver/excluded_geographical_areas_spec.rb
spec/unit/form_savers/measure_saver/footnote_spec.rb
spec/unit/form_savers/measure_saver/measure_condition_spec.rb
spec/unit/form_savers/measure_saver/measure_spec.rb
spec/unit/form_savers/measure_saver/quota_definition_spec.rb

[TRELLO CARD](https://trello.com/c/fB2ulVCR/151-refactor-code-and-write-automated-tests-18)

[MEASURE SAVER] Rspec Unit tests pack

---

Gemfile.lock

Fix via upgrading from 'sprockets' **3.7.1** to **3.7.2**
[MORE DETAILS ABOUT ISSUE](https://groups.google.com/forum/#!topic/rubyonrails-security/ft_J--l55fMhttps://groups.google.com/forum/#!topic/rubyonrails-security/ft_J--l55fM)
[TRELLO CARD](https://trello.com/c/qFsTdEOC/2245-dit-rails-security-issue-path-traversal-in-sprockets)

[SECURITY UPDATES] fix vulnerability in Sprockets.

---

Gemfile.lock

Fix via upgrading from 'sprockets' **3.7.1** to **3.7.2**
[MORE DETAILS ABOUT ISSUE](https://groups.google.com/forum/#!topic/rubyonrails-security/ft_J--l55fMhttps://groups.google.com/forum/#!topic/rubyonrails-security/ft_J--l55fM)
[TRELLO CARD](https://trello.com/c/qFsTdEOC/2245-dit-rails-security-issue-path-traversal-in-sprockets)

[SECURITY UPDATES] fix vulnerability in Sprockets. [STAGING RELEASE]

---

app/assets/javascripts/components/bulk-edit-measures.js
app/assets/javascripts/vue_components/change-regulation-popup.js
app/assets/javascripts/vue_components/change-validity-period-popup.js
app/models/concerns/form_api_helpers/regulation_search.rb
app/views/measures/bulks/edit.html.slim

https://trello.com/c/Y8EUQWZM/334-dit-bulk-edit-frontend-when-we-are-clicking-on-update-selected-measures-in-change-validity-period-or-regulation-popup-measures-j

UI fixes for bulk-edit-popups

---

app/assets/javascripts/vue_components/remove-measures-popup.js
app/assets/stylesheets/components/alert.scss
app/assets/stylesheets/components/modal.scss
app/views/shared/vue_templates/_remove_measures.html.erb

https://trello.com/c/UpiCPjJo/316-dit-bulk-edit-popups-removal-4

remove measures from group - handle server failures

---

app/assets/javascripts/vue_components/delete-measures-popup.js
app/views/measures/bulks/edit.html.slim
app/views/shared/vue_templates/_delete_measures.html.slim

https://trello.com/c/tIWHH8VQ/315-dit-bulk-edit-popups-delete-45

bulk delete measures

---

app/assets/javascripts/components/bulk-edit-measures.js
app/assets/javascripts/vue_components/change-commodity-code-popup.js
app/assets/javascripts/vue_components/measure-change-commodity-code-input.js
app/assets/javascripts/vue_components/measure-commodity-code-previewer.js
app/assets/stylesheets/bootstrap_overrides.scss
app/views/measures/bulks/edit.html.slim
app/views/shared/vue_templates/_change_commodity_codes.html.erb
app/views/shared/vue_templates/_delete_measures.html.slim

https://trello.com/c/k5WGuWCc/311-dit-bulk-edit-popups-commodity-code-55

bulk update measures commodity codes

---

app/controllers/measures/bulks_controller.rb
app/controllers/workbaskets/create_measures_controller.rb
app/interactors/workbaskets/create_measures/saver.rb
app/models/workbaskets/create_measures_settings.rb
app/models/workbaskets/workbasket.rb
config/routes.rb
db/migrate/20180709182215_create_create_measures_workbasket_settings.rb
db/migrate/20180709182401_add_settings_jsonb_to_create_measures_workbasket_settings.rb
db/migrate/20180709182617_add_timestamps_to_create_measures_workbasket_settings.rb
db/structure.sql

[TRELLO CARD](https://trello.com/c/IN154EvH/204-dit-create-measures-iteration)

[CREATE MEASURES V2] add base sceleton for V2 version (separated namespace, controllers, new associations so on)

---

app/assets/javascripts/components/bulk-edit-measures.js
app/assets/javascripts/vue_components/change-additional-code-popup.js
app/assets/javascripts/vue_components/change-commodity-code-popup.js
app/assets/javascripts/vue_components/measure-additional-code-previewer.js
app/assets/javascripts/vue_components/measure-change-additional-code-input.js
app/assets/stylesheets/simple-grid.scss
app/views/measures/bulks/edit.html.slim
app/views/shared/vue_templates/_change_additional_code.html.slim

https://trello.com/c/CwxABsek/312-dit-bulk-edit-popups-additional-code-6

bulk edit - change additional codes

---

app/assets/javascripts/components/bulk-edit-measures.js
app/assets/javascripts/vue_components/change-footnotes-popup.js
app/assets/javascripts/vue_components/delete-measures-popup.js
app/assets/javascripts/vue_components/footnote.js
app/assets/stylesheets/components/footnote.scss
app/views/measures/bulks/edit.html.slim
app/views/shared/vue_templates/_change_footnotes.html.slim
app/views/shared/vue_templates/_footnote.html.slim
app/views/shared/vue_templates/_measures_grid.html.erb

for bulk-edit measures
https://trello.com/c/XOvqXITQ/314-dit-bulk-edit-popups-footnotes-5

change footnotes popup

---

app/assets/javascripts/components/measure_form.js
app/views/workbaskets/create_measures/steps/main/_check_a_additional_code_description.html.slim

[TRELLO CARD](https://trello.com/c/IN154EvH/204-dit-create-measures-iteration)

[CREATE MEASURES V2] Preview JS functionality for 'Check a additional code description' 

---

app/assets/javascripts/vue_components/change-footnotes-popup.js
app/views/shared/vue_templates/_change_footnotes.html.slim

https://trello.com/c/XOvqXITQ/314-dit-bulk-edit-popups-footnotes-5

minor tweaks in bulk-edit footnotes popup

---

app/assets/javascripts/vue_components/change-origins-popup.js
app/assets/javascripts/vue_components/measure-origin.js
app/assets/stylesheets/components/modal.scss
app/forms/measure_form.rb
app/forms/workbaskets/create_measures/form.rb
app/views/measures/bulks/edit.html.slim
app/views/shared/vue_templates/_change_origins.html.erb
app/views/shared/vue_templates/_measure_origin.html.slim

https://trello.com/c/4N0G8aqH/310-dit-bulk-edit-popups-origins-55

bulk edit measures: change origin popup

---

app/models/commodity.rb
app/value_objects/create_measures/attributes_parser.rb
app/value_objects/create_measures/commodity_code_parser.rb
app/value_objects/create_measures/validation_helpers/excluded_geographical_areas.rb
app/value_objects/measures/attributes_normalizer.rb

**1) Fix issue with missing excluded geographical area**
Related SENTRY issue https://sentry.io/bit-zesty-client-apps/management/issues/626625741
**2) Fix issue with detection of commodity codes of '0101210000'**
[TRELLO CARD](https://trello.com/c/IN154EvH/204-dit-create-measures-iteration)

[CREATE MEASURES V2] Bugfixes

---

app/assets/javascripts/components/measure_form.js
app/assets/javascripts/components/workbaskets/save-actions.js.coffee
app/models/workbaskets/workbasket.rb

[TRELLO CARD](https://trello.com/c/Gz8poDyu/225-dit-as-a-tariff-manager-i-want-to-create-a-new-quota-and-related-data-108)

[CREATE QUOTA] Fixed JS Navigation issue with 'Continue' button

---

app/assets/javascripts/components/measure_form.js
app/assets/javascripts/components/workbaskets/create-quota.js.coffee
app/assets/stylesheets/components/workbasket_create_quota.scss
app/controllers/workbaskets/base_controller.rb
app/controllers/workbaskets/create_measures_controller.rb
app/controllers/workbaskets/create_quota_controller.rb
app/forms/workbasket_forms/create_quota_form.rb
app/helpers/measures_helper.rb
app/helpers/workbasket_helper.rb
app/interactors/workbasket_interactions/settings_saver_base.rb
app/models/concerns/workbasket_helpers/settings_base.rb
app/models/workbaskets/create_measures_settings.rb
app/models/workbaskets/create_quota_settings.rb
app/models/workbaskets/workbasket.rb
app/value_objects/workbasket_value_objects/create_quota/attributes_parser.rb
app/value_objects/workbasket_value_objects/create_quota/step_pointer.rb
app/views/workbaskets/create_measures/steps/_main.html.slim
app/views/workbaskets/create_quota/steps/_main.html.slim
app/views/workbaskets/create_quota/steps/main/_licensed_block.html.slim
app/views/workbaskets/create_quota/steps/main/_order_number.html.slim
app/views/workbaskets/create_quota/steps/main/_order_number_description.html.slim
app/views/workbaskets/shared/steps/main/_measure_type.html.slim
app/views/workbaskets/shared/steps/main/_regulation.html.slim
config/locales/en.yml

[TRELLO CARD](https://trello.com/c/Gz8poDyu/225-dit-as-a-tariff-manager-i-want-to-create-a-new-quota-and-related-data-108)

[CREATE QUOTA] BACKEND + FRONTEND - work in progress

---

app/assets/javascripts/vue_components/date-select.js
app/views/shared/vue_templates/_date_select.html.slim

Reverting datepicker -> 3-select change as it was a result of a misinterpretation during a call with client.
Reverted to the way they were previous to PR #135

Reverting date selections to datepickers

---

app/assets/javascripts/components/measure_form.js
app/controllers/workbaskets/base_controller.rb
app/interactors/workbasket_interactions/settings_saver_base.rb
app/value_objects/workbasket_value_objects/create_quota/attributes_parser.rb
app/value_objects/workbasket_value_objects/create_quota/step_pointer.rb
app/views/home/index.html.slim

[TRELLO CARD](https://trello.com/c/Gz8poDyu/225-dit-as-a-tariff-manager-i-want-to-create-a-new-quota-and-related-data-108)

[CREATE QUOTA] Backend: saving functionality fixes

---

app/controllers/measures/bulks_controller.rb
app/views/home/index.html.slim
app/views/measures/bulks/edit.html.slim
app/views/workbaskets/create_measures/steps/_duties_conditions_footnotes.html.slim
app/views/workbaskets/create_quota/steps/_conditions_footnotes.html.slim
app/views/workbaskets/shared/steps/duties_conditions_footnotes/_conditions.html.slim
db/migrate/20180807180500_add_initial_search_results_code_to_workbaskets.rb
db/structure.sql
lib/trade_tariff_backend.rb

**1) [BULK EDIT OF MEASURES] 'Work with selected measures' section: added 'Back' link**
[TRELLO STORY](https://trello.com/c/Gr3Pyle1/379-dit-breadcrumbs-so-you-can-go-back-after-conducting-a-search-for-measures)
**2) [Code review updates] let's use TradeTariffBackend class**
**3) [CREATE QUOTA] Frontend: Step 3: small copy tweaks**
[TRELLO CARD](https://trello.com/c/Gz8poDyu/225-dit-as-a-tariff-manager-i-want-to-create-a-new-quota-and-related-data-108)

[BULK EDIT OF MEASURES] 'Work with selected measures' section: added 'Back' link     

---

app/assets/javascripts/components/bulk-edit-measures.js
app/assets/javascripts/vue_components/measures-grid.js
app/assets/stylesheets/components/modal.scss

https://trello.com/c/UpiCPjJo/316-dit-bulk-edit-popups-removal-4

bulk actions: enhances to remove measures from group action

---

app/assets/javascripts/vue_components/change-additional-code-popup.js
app/assets/javascripts/vue_components/change-footnotes-popup.js
app/assets/javascripts/vue_components/measure-change-additional-code-input.js
app/views/shared/vue_templates/_change_additional_code.html.slim
app/views/shared/vue_templates/_change_footnotes.html.slim
app/views/shared/vue_templates/_footnote.html.slim

https://trello.com/c/XOvqXITQ/314-dit-bulk-edit-popups-footnotes-5
https://trello.com/c/CwxABsek/312-dit-bulk-edit-popups-additional-code-6#

bulk edit: footnotes enhances

---

app/assets/javascripts/components/find-measures.js
app/controllers/measures/bulks_controller.rb
app/controllers/workbaskets/base_controller.rb
app/interactors/workbasket_interactions/submit_for_cross_check_base.rb
app/models/measure.rb
app/models/workbaskets/event.rb
app/models/workbaskets/workbasket.rb
app/tasks/measures/set_published_status.rb
app/value_objects/workbasket_value_objects/shared/system_ops_assigner.rb
app/workers/searchable_data_reindex_worker.rb
app/workers/temporary_workers/set_published_status_worker.rb
config/locales/en.yml
lib/chief_transformer/candidate_measure.rb
spec/factories/workbasket_code_factory.rb
spec/support/shared_contexts/xml_generation/record_context.rb
spec/unit/searches/measures/status_filter_spec.rb
spec/xml_generation/main_spec.rb

[TRELLO CARD](https://trello.com/c/ZWc5B5WK/349-dit-update-status-values-in-search-filter-and-make-all-existing-data-published)

[RECORD STATES] update workbasket system to work with new states

---

app/assets/javascripts/vue_components/change-conditions-popup.js
app/assets/javascripts/vue_components/change-duties-popup.js
app/assets/javascripts/vue_components/components-coordinator.js
app/assets/javascripts/vue_components/conditions-coordinator.js
app/assets/javascripts/vue_components/measure-components.js
app/assets/javascripts/vue_components/measure-condition.js
app/assets/javascripts/vue_components/popup.js
app/assets/stylesheets/components/forms.scss
app/assets/stylesheets/components/measure-components.scss
app/assets/stylesheets/components/measure-condition-component.scss
app/assets/stylesheets/components/measure-condition.scss
app/assets/stylesheets/simple-grid.scss
app/views/measures/measures/form_parts/_conditions.html.slim
app/views/measures/measures/form_parts/_duty_expression.html.slim
app/views/shared/vue_templates/_change_conditions.html.erb
app/views/shared/vue_templates/_change_duties.html.erb
app/views/shared/vue_templates/_condition.html.slim
app/views/shared/vue_templates/_measure_component.html.slim
app/views/shared/vue_templates/_measure_condition_component.html.slim
app/views/workbaskets/create_measures/steps/duties_conditions_footnotes/_duty_expression.html.slim
app/views/workbaskets/shared/steps/duties_conditions_footnotes/_conditions.html.slim

This PR accomplishes the following:
- Fixes issue when opening certain measures for editing conditions
- Changes conditions layout to match designs
- Changes measure components to match designs

Fixes for conditions popup bulk editing

---

app/assets/javascripts/vue_components/change-commodity-code-popup.js
app/assets/javascripts/vue_components/measure-change-commodity-code-input.js
app/views/shared/vue_templates/_change_commodity_codes.html.erb

https://trello.com/c/k5WGuWCc/311-dit-bulk-edit-popups-commodity-code-55

bulk edit: commodity code enhances

---

app/forms/workbasket_forms/base_form.rb
lib/measures/refresh_cache.rb

[TRELLO CARD](https://trello.com/c/SZpxy72p/404-creating-tariff-preference-142-measure-is-stuck-with-checking-data-when-all-the-data-entered-and-clicked-on-next-on-second-page)

[CACHE REFRESH SCRIPT] updates and bugfixes

---

app/assets/javascripts/vue_components/change-commodity-code-popup.js
app/assets/javascripts/vue_components/measure-change-commodity-code-input.js
app/assets/stylesheets/components/forms.scss
app/assets/stylesheets/simple-grid.scss
app/views/shared/vue_templates/_change_commodity_codes.html.erb

& minor enhances to UI
https://trello.com/c/k5WGuWCc/311-dit-bulk-edit-popups-commodity-code-55

validate commodity codes before updating

---

app/assets/javascripts/components/bulk-edit-measures.js

https://trello.com/c/zgjMO6Mg/355-dit-deleting-an-item-should-keep-it-there-and-strikethrough-the-text-35

strikethrough deleted measures in grid

---

.rubocop.yml
Gemfile
app/assets/javascripts/components/workbaskets/validation_errors_handler.js.coffee
app/interactors/workbasket_interactions/create_measures/settings_saver.rb
app/interactors/workbasket_interactions/settings_saver_base.rb
app/models/additional_code_type.rb
app/models/commodity.rb
app/models/goods_nomenclature.rb
app/models/workbaskets/item.rb
app/models/workbaskets/workbasket.rb
app/services/workbasket_services/quota_savers/base_period.rb
app/value_objects/measures/attributes_normalizer.rb
app/value_objects/workbasket_value_objects/attributes_parser_base.rb
app/value_objects/workbasket_value_objects/shared/additional_codes_analyzer.rb
app/value_objects/workbasket_value_objects/shared/commodity_code_parser.rb
app/value_objects/workbasket_value_objects/shared/commodity_codes_analyzer.rb
app/views/workbaskets/create_measures/_form.html.slim
app/views/workbaskets/create_measures/steps/review_and_submit/_measures_table.html.slim
app/views/workbaskets/create_quota/steps/review_and_submit/_measures_table.html.slim
config/environments/development.rb
config/environments/test.rb
config/initializers/raven.rb
spec/support/shared_contexts/form_savers/measure_saver_base_context.rb
spec/unit/form_savers/measure_saver/measure_spec.rb

Fixes issue with quota measures and bulk created measures not saving additional codes. 
It was also also not behaving as expected:
> "Separate measures will be created for every combination of commodity code and additional code"
Breaks slightly the display of errors, but I can live with that for now, as we need this working asap.

Refactor measure saver

---

app/assets/javascripts/components/measure_form.js
app/assets/javascripts/components/utils.js
app/assets/javascripts/vue_components/quota-section.js
app/controllers/measures/measure_type_series_controller.rb
app/models/measure_type.rb
app/models/measure_type_series.rb
app/views/measures/measures/_search_form.html.erb
app/views/shared/vue_templates/_date_select.html.slim
app/views/shared/vue_templates/_opening_balances_manager.html.erb
app/views/workbaskets/create_quota/steps/main/_order_number.html.slim
app/views/workbaskets/shared/steps/main/_measure_type.html.slim

This PR implements a couple frontend fixes:
- Limits order number length to 6 and prefills it with "09"
- Fixes opening balances for quotas
- On create measures, remove all quota related measure types
- on create quotas, remove all non-quota measure types
- disable autofill for date selects

Stable frontend fixes

---

app/assets/javascripts/vue_components/conditions-coordinator.js
app/assets/javascripts/vue_components/measure-condition.js

Allowing user to select certificate type for condition type A

---

Gemfile
Gemfile.lock
app/services/workbasket_services/measure_association_savers/footnotes.rb

swap 2 records inside workbasket.

fix footnote description period and footnote sequence.

---

app/controllers/workbaskets/create_regulation_controller.rb
app/validators/measure_validator.rb

1) Measure validator: fixed ME116
2) Create Regulation: fixed issue with redirect on Submit and Review action
[TRELLO CARD](https://trello.com/c/dMAf97m1/434-edit-measures-functionality-not-working-eg-edit-the-measure-with-end-date-or-regulation-6)

[TESTING ROUND] bugfixes detected while testing

---

app/assets/javascripts/components/bulk-edit-measures.js
app/assets/javascripts/vue_components/change-validity-period-popup.js
app/assets/javascripts/vue_components/measures-grid.js
app/assets/stylesheets/components/layout.scss
app/views/shared/vue_templates/_change_validity_period.html.erb
app/views/workbaskets/create_measures/_form.html.slim
app/views/workbaskets/create_quota/_form.html.slim
app/views/workbaskets/shared/_errors_container.html.slim

This PR deploys #191  and #192  to staging

Deploying latest fixes to staging

---

app/assets/javascripts/components/bulk-edit-measures.js
app/assets/javascripts/components/measure-condition-formatter.js
app/assets/javascripts/components/work-with-selected-measures.js
app/assets/javascripts/vue_components/change-conditions-popup.js
app/assets/javascripts/vue_components/change-duties-popup.js
app/assets/javascripts/vue_components/change-validity-period-popup.js
app/assets/javascripts/vue_components/custom-select.js
app/assets/stylesheets/components/tables.scss
app/controllers/measures/bulks_controller.rb
app/interactors/workbasket_interactions/bulk_edit_of_measures/item_saver.rb
app/models/measure.rb
app/views/measures/bulks/work_with_selected_measures.html.erb

justification regulation fixed on end dated measure.
fixed justification regulation column on edit measure screen.

More bulk edit fixes

---

app/assets/javascripts/components/duty-expressions-parser.js

fixed + and - for few duty expressions.

---

app/assets/javascripts/components/find-measures.js

disable search fields by default.

disable search fields by default.

---

app/models/xml_generation/node_envelope.rb
app/models/xml_generation/node_transaction.rb

fixed transaction id and envelope id for xml export.

fixed transaction id and envelope id for xml export.

---

app/value_objects/workbasket_value_objects/shared/commodity_code_parser.rb
app/value_objects/workbasket_value_objects/shared/commodity_codes_analyzer.rb

I replaced the complex logic of goods nomenclature expanding with the single sql query. It fast, and I hope that it easy to understand and maintain.
0. If we have no excluded codes list, we create measures for all codes.
1. If some code has an excluded child:
a. If the code is a chapter, we should check all the headings. 
- If the heading has an excluded child, expand it to declarable children and create new measures for all codes minus excluded. 
- If the heading has no excluded child, create a new measure for heading.
b. If the code is not a chapter, expand it to declarable children and create new measures for all codes minus excluded.
2. If some code has no excluded child, create a new measure for the code.

Excluded measure logic

---

app/assets/stylesheets/components/forms.scss
app/views/shared/vue_templates/_change_additional_code.html.slim
app/views/shared/vue_templates/_change_commodity_codes.html.erb

Fields were horizontally misaligned
Changed html structure to level them out.

Fix additional code fields alignment

---

app/assets/javascripts/components/bulk-edit-measures.js
app/assets/javascripts/components/utils.js
app/views/measures/bulks/edit.html.slim

Previously we were not retrying requests AT ALL.
Implementing 10 retries
after that a pause of 30s is given before trying again

Never give up loading measures in bulk edit!

---

app/assets/javascripts/vue_components/popup.js

Title pretty self explanatory.

Making popup window receive focus on open, so datepickers don't auto-open

---

app/assets/javascripts/components/measure_form.js
app/assets/javascripts/components/quota-form.js
app/assets/javascripts/components/regulation-form.js
app/assets/javascripts/components/workbaskets/save-actions.js.coffee
app/assets/javascripts/components/workbaskets/validation_errors_handler.js.coffee
app/assets/javascripts/vue_components/icon-success.js
app/assets/javascripts/vue_components/success-message.js
app/assets/stylesheets/components/alert.scss
app/views/workbaskets/shared/_errors_container.html.slim
app/views/workbaskets/shared/_success_message.html.slim

Implementing proper "Progress saved" message in green as opposed to leaving it right above error messages in red.
Also took the opportunity to do some refactorings.

Implementing proper positive feedback from designs + refactorings

---

app/assets/javascripts/components/find-measures.js
app/views/measures/measures/_search_form.html.erb
app/views/measures/measures/search_form_parts/_measure_sid_filter.html.erb

- Selections are all OFF initially
- Fields are no longer disabled by default
- Checkboxes are turned on whenever the user makes a selection or changes values

Fixing UX of find a measure filters

---

app/assets/javascripts/components/utils.js
app/assets/javascripts/components/xml-generation-form.js
app/views/shared/base_export/_form.html.slim

To really make sure it won't autofill again, I'm randomizing a "autocomplete" field on every page load, so the browser always looks up something different.

Randomizing autocomplete attribute to trick browsers

---

app/controllers/workbaskets/create_regulation_controller.rb
app/helpers/workbasket_helper.rb
app/views/workbaskets/_main_menu.html.slim
app/views/workbaskets/_table.html.slim

[TRELLO STORY](https://trello.com/c/Ga1BVjvo/294-dit-as-a-tariff-manager-i-want-a-main-menu-so-that-i-can-access-various-manage-create-find-edit-screens-plus-a-list-of-anything)

[MAIN MENU] UI tweaks + Logic of displaying of 'View' link for Workbaskets

---

app/views/shared/vue_templates/_quota_section.html.erb

Hiding repeat checkbox from custom periods

---

app/assets/javascripts/components/duty-expression-formatter.js
app/assets/javascripts/vue_components/change-duties-popup.js
app/views/measures/bulks/_table_top.html.erb

- Duties were rendering weird abbreviations
- When there were multiple duities per measure, the "equal" detection was not accurately detecting

Fixing rendering of duties + fixing detection of equal duties in bulk edit

---

app/controllers/concerns/base_job_mixin.rb
app/services/xml_generation/taric_export.rb
app/services/xml_generation/xml_interactor_base.rb

Ne filename format: 
```
DIT_<Start Date - YYYYMMDD>-<End Date -YYYYMMDD>-<Timestamp - YYYYMMDDTHHMMSS>-EUFileSequence.XML
```

[xml export] Change exported xml filename, minor refactoring

---

app/assets/javascripts/components/bulk-edit-measures-save-actions.js.coffee
app/controllers/measures/bulks_controller.rb
app/views/measures/bulks/submitted_for_cross_check.html.slim
config/initializers/rack_timeout.rb
config/routes.rb

- If no conformance errors, don't show popup and redirect directly
- If there are conformance errors, then display popup
- Fixed issue of wrong regulation being set as generating regulation
- Implemented submitted for cross check page as well

Fix conformance errors popup

---

app/assets/stylesheets/components/tables.scss
app/controllers/workbaskets/create_quota_controller.rb
app/interactors/workbasket_interactions/create_quota/settings_saver.rb
app/models/quota_association.rb
app/models/quota_definition.rb
app/models/quota_order_number.rb
app/models/workbaskets/create_quota_settings.rb
app/services/workbasket_services/quota_savers/parent_quota.rb
app/services/workbasket_services/quota_savers/sub_quota.rb
app/value_objects/workbasket_value_objects/create_quota/attributes_parser.rb
app/views/workbaskets/create_quota/steps/_review_and_submit.html.slim
app/views/workbaskets/create_quota/steps/review_and_submit/_parent_quotas.html.slim
app/views/workbaskets/create_quota/steps/review_and_submit/_parent_quotas_table.html.slim
app/views/workbaskets/create_quota/steps/review_and_submit/_quota_periods_table.html.slim
app/views/workbaskets/create_quota/steps/review_and_submit/_sub_quotas.html.slim
app/views/workbaskets/create_quota/steps/review_and_submit/_sub_quotas_table.html.slim
db/migrate/20180925161300_add_parent_quota_period_sids_to_create_quota_settings.rb
db/structure.sql

reworked quota association - now it's created for quota definition entities, not for order numbers.
added parent quota table on Review and submit screen.
added sub-quotas table on Review and submit screen.
fixed sub-quotas create measure behavior for multiple goods nomenclatures.

Quota association fix

---

app/assets/javascripts/components/workbaskets/validation_errors_handler.js.coffee
app/interactors/workbasket_interactions/create_quota/settings_saver.rb
app/services/workbasket_services/quota_savers/parent_quota.rb
app/services/workbasket_services/quota_savers/sub_quota.rb
app/views/workbaskets/create_quota/steps/review_and_submit/_sub_quotas_table.html.slim
app/views/workbaskets/shared/_custom_errors_block.html.slim

added parent and sub-quotas association validation.
fixed Review and submit crash if no sub-quotas added.

Quota association validation

---

app/decorators/job_base_decorator.rb
app/services/xml_generation/node_envelope.rb
app/services/xml_generation/taric_export.rb

[xml export] Do not generate xml files if there are no records to export

---

app/models/db/rollback_process.rb
app/models/xml_generation/workbasket_search.rb

[SENTRY](https://sentry.io/bit-zesty-client-apps/management/issues/703426188/)

[DB ROLLBACKS] fixed issue cleaning up

---

app/interactors/measures/workbasket/items.rb
app/models/geographical_area.rb

[TRELLO CARD](https://trello.com/c/NR4Bxeiz/533-dit-investigate-server-error)

[BULK EDIT OF MEASURES] Bugfixes

---

Gemfile
Gemfile.lock
app/assets/javascripts/components/bulk-edit-measures.js
app/interactors/measures/workbasket/items.rb
app/models/geographical_area.rb
app/searches/shared/search_filters/date_universal.rb
app/views/measures/bulks/edit.html.slim

[TRELLO STORY](https://trello.com/c/NR4Bxeiz/533-dit-investigate-server-error)

Bulk edit of measures bugfixes v1
