app/assets/javascripts/components/measure_form.js
app/assets/stylesheets/components/forms.scss
app/forms/measure_form.rb
app/views/measures/measures/_form.html.slim
app/views/measures/measures/_js_variables.html.erb
app/views/measures/measures/form_parts/_geographical_area.html.slim
app/views/shared/vue_templates/_measure_origin.html.slim

Rewriting the whole origin section to be able to fix issue of VueJS re-rendering the form, losing the origin section customisations.

Rewriting measure origins

---

app/controllers/db/rollbacks_controller.rb
app/decorators/application_decorator.rb
app/decorators/db/rollback_decorator.rb
app/decorators/job_base_decorator.rb
app/decorators/xml_export/file_decorator.rb
app/models/db/rollback.rb
app/models/db/rollback_process.rb
app/models/xml_generation/search.rb
app/views/db/rollbacks/_form.html.slim
app/views/db/rollbacks/_table.html.slim
app/views/db/rollbacks/index.html.slim
app/views/home/index.html.slim
app/workers/db/rollback_worker.rb
config/routes.rb
db/migrate/20180410100532_create_db_rollbacks.rb
db/structure.sql
lib/sequel/plugins/oplog.rb

1) DB Rollbacks: implemented ability to clear all data from the db from an operational date
[TRELLO CARD](https://trello.com/c/mjslkrQF/149-delete-data-from-an-operational-date)
2) XML Exporter: fixed issue with missing db records in XML:
- MeasurePartialTemporaryStop
- MeasureExcludedGeographicalArea
- FootnoteAssociationErn

[DB Rollbacks] Ability to clear data from an operational date

---

app/assets/javascripts/components/measure_form.js
app/controllers/additional_codes/additional_code_types_controller.rb
app/interactors/measure_saver.rb
app/models/additional_code_type.rb
app/models/measure_type.rb
app/views/measures/measures/form_parts/_goods_nomenclature.html.slim

1)  'Additional code types' select should be pre-populated with additional code types related to specified measure type (via AdditionalCodeTypeMeasureType db record)
[TRELLO CARD](https://trello.com/c/WKRFV0rg/169-measure-form-additional-code-types-select-should-be-pre-populated-with-additional-code-types-related-to-specified-measure-type-v)
2) Measure saver: fixed issue with assigning of Heading for Measure. Previously used code was working with Commodities only (and was ignoring Headings)
[SENTRY ISSUE](https://sentry.io/bit-zesty-client-apps/management/issues/526975545/)

Measure saver bug fix + Additional Code Type updates

---

app/assets/javascripts/components/custom-select.js
app/assets/javascripts/components/measure_form.js
app/assets/stylesheets/components/select.scss
app/views/measures/measures/form_parts/_goods_nomenclature.html.slim
app/views/measures/measures/form_parts/_quota.html.slim
app/views/measures/measures/form_parts/_reference_price.html.slim
app/views/measures/measures/form_parts/_standart_import_value.html.slim
app/views/measures/measures/form_parts/_unit_price.html.slim
app/views/regulations/_form.html.slim
app/views/shared/vue_templates/_condition.html.slim
app/views/shared/vue_templates/_footnote.html.slim
app/views/shared/vue_templates/_measure_component.html.slim
app/views/shared/vue_templates/_measure_condition_component.html.slim
app/views/shared/vue_templates/_measure_origin.html.slim
app/views/shared/vue_templates/_quota_period.html.slim

Measurement units and duty expression codes have abbreviations which are
more commonly used in place of the description or code, so makes sense
to use them.
Also took the time to properly align all dropdown codes with their
descriptions so not too much nor too little spacing was between them.
**ps: I know this is stuff related mostly to measure form, but since regulations-form branch has the most up-to-date code, made sense to me to PR against it**

Adding abbreviations to dropdown selects

---

app/assets/javascripts/components/measure_form.js
app/assets/javascripts/vue_components/custom-select.js
app/assets/javascripts/vue_components/measure-components.js
app/assets/stylesheets/components/forms.scss
app/assets/stylesheets/simple-grid.scss
app/views/shared/vue_templates/_measure_component.html.slim
app/views/shared/vue_templates/_measure_condition_component.html.slim

Separating "% or amount" duty expressions logically on the frontend so
users can select more appropriate options, and have the UI change
accordingly.
Affected expressions: 01, 02, 04, 19, 20

Making duty expressions easier to select and fill

---

Gemfile
Gemfile.lock

Snyk detected possible vulnerability in 'sinatra' gem less than '2.0.2'
[SNYK REPORTED ISSUE DETAILS](https://snyk.io/vuln/SNYK-RUBY-SINATRA-22027?utm_source=slack)
[TRELLO CARD](https://trello.com/c/s0cA5djh/218-update-gems-for-security-across-app-tariff-apps)

[SECURITY UPDATES] updated 'sinatra' gem to '2.0.2'

---

.gitignore
app/assets/javascripts/application.js
app/assets/javascripts/components/bulk-edit-measures.js
app/assets/javascripts/components/db.js
app/assets/javascripts/components/find-measures.js
app/assets/javascripts/vendors/dexie.js
app/assets/javascripts/vue_components/loading-indicator.js
app/assets/javascripts/vue_components/loading-spinner.js
app/assets/javascripts/vue_components/measures-grid.js
app/assets/stylesheets/components/find-measures.scss
app/assets/stylesheets/components/loading-indicator.scss
app/assets/stylesheets/components/loading-spinner.scss
app/assets/stylesheets/components/tables.scss
app/controllers/concerns/search_cache_helpers.rb
app/controllers/measures/bulks_controller.rb
app/controllers/measures/measures_controller.rb
app/searches/measures/search.rb
app/services/measure_service/fetch_measure_sids.rb
app/services/measure_service/track_measure_sids.rb
app/views/measures/bulks/edit.html.slim
app/views/measures/measures/_measures_table.html.erb
app/views/measures/measures/_search_page.html.slim
app/views/measures/measures/work_with_selected_measures.html.erb
app/views/shared/vue_templates/_measures_grid.html.erb
config/initializers/kaminari_config.rb

New Approach of pagination of measures, selected in 'Find measures' screen:
**STEP 1: User does search in 'Find Measures' form**
We are caching search params to Redis and allocating unique search code to that search query.
Then app redirects user to search results url with search code in it.
**EG:**
`/measures/bulks/4/edit?search_code=18_BE_1529423586`
Also system puts into Redis cache measure_ids for all records, returned in search results.
**STEP 2: User selects measures and clicks on 'Work with selected measures' button**
Frontend sends POST request to server url 'measures/bulks' with body:
```
{
selection_type: all or none,
measure_sids: [array of measure_sids]
}
```
Idea is the following:
- instead of passing all selected measure_sids
- use two params to handle …

[BULK EDIT - PAGINATION] speed performance improvements

---

app/assets/javascripts/components/bulk-edit-measures.js
app/models/measure.rb

Currently it looks like:
```
"additional_code"=>{"type_id"=>"2", "description"=>"Imported by land, inland waterway or sea or imported by air.", "additional_code"=>"550"}
```
We do not need such more values, we need just code here:
```
"additional_code"=>"[CODE HERE]"
```
EG:
```
"additional_code"=>"2550"
```
[TRELLO CARD](https://trello.com/c/u1DAWOlM/344-dit-bulk-edit-additional-code-update-json-object-key-options-to-more-usefull)

Bulk Edit - Additional Code update JSON object key options to more usefull

---

app/interactors/regulation_saver.rb

SENTRY ISSUE RELATED: https://sentry.io/bit-zesty-client-apps/management/issues/602327087/
Issue happens if submit blank form.
[TRELLO CARD](https://trello.com/c/9SCluIDP/346-dit-create-regulations-sentry-reported-issue-wrong-constant-name-requiredparams-https-sentryio-bit-zesty-client-apps-management)

[DIT] Create regulations - SENTRY reported issue 'wrong constant name_REQUIRED_PARAMS'

---

app/assets/javascripts/application.js
app/assets/javascripts/components/bulk-edit-measures.js
app/assets/javascripts/components/measure-condition-formatter.js
app/assets/javascripts/components/utils.js
app/assets/javascripts/vue_components/change-conditions-popup.js
app/assets/javascripts/vue_components/change-duties-popup.js
app/assets/javascripts/vue_components/loading-indicator.js
app/assets/javascripts/vue_components/measure-components.js
app/assets/javascripts/vue_components/measure-condition.js
app/assets/javascripts/vue_components/measures-grid.js
app/assets/javascripts/vue_components/popup.js
app/assets/stylesheets/components/forms.scss
app/assets/stylesheets/components/layout.scss
app/assets/stylesheets/components/modal.scss
app/assets/stylesheets/components/tables.scss
app/models/measure_condition.rb
app/views/measures/bulks/edit.html.slim
app/views/shared/vue_templates/_change_conditions.html.erb
app/views/shared/vue_templates/_change_duties.html.erb
app/views/shared/vue_templates/_condition.html.slim
app/views/shared/vue_templates/_measure_component.html.slim
app/views/shared/vue_templates/_measure_condition_component.html.slim

This PR accomplishes the following on the Bulk Edit flow:
- Implements amount field validation in duties popup
- Implements the Change Conditions popup
- Plus, fixes some small issues:
- Removes unnecessary bulk actions (make copies, change quota and change status)
- Fixes select all checkbox in bulk edit screen
- Fixes loading indicator start/end numbers
- Fixes editing measures without commodity code
- Fixes empty end date
- Fixes table cells collapsing when they have no content
- Fixes measure condition component serialization in models

Bulk edit popup fixes

---

app/forms/measure_form.rb
app/workers/refresh_cache_worker.rb
config/sidekiq.yml
lib/tasks/measures/refresh_cache.rb

Improve mechanism of caching geographical areas collection for 'Which origin will the measures apply to?' block.
Currently sometimes it raising 'Rack::Timeout' issues on server when user opening 'Create measures' section
Related sentry issue https://sentry.io/bit-zesty-client-apps/management/issues/611373879/
[TRELLO CARD](https://trello.com/c/IN154EvH/204-dit-create-measures-iteration)

[CREATE MEASURES V2 - BACKEND] Improve mechanism of caching geographical areas collection

---

app/assets/stylesheets/components/modal.scss
app/views/shared/vue_templates/_change_additional_code.html.slim
app/views/shared/vue_templates/_change_footnotes.html.slim

replace default browser elements with custom govuk radio buttons & checkboxes
for change footnotes and change additional codes actions

use govuk elements in bulk edit modals

---

app/controllers/measures/measures_controller.rb
app/helpers/measures_helper.rb
app/views/regulations/search/_results.html.slim
config/routes.rb

The searching link on regulations listing does not pre fill the measure search with the regulation id
[TRELLO CARD](https://trello.com/c/2s6f7Ipj/341-dit-the-searching-link-on-regulations-listing-does-not-pre-fill-the-measure-search-with-the-regulation-id-1)

[Find Regulation] fix [measures] link search

---

app/searches/measures/search_filters/footnotes.rb

Selecting Footnotes are not unspecified or specified breaks search
[TRELLO STORY](https://trello.com/c/6IMJLeIg/378-dit-selecting-footnotes-are-not-unspecified-or-specified-breaks-search)

[FIND MEASURES] Fix 'Footnotes' filters

---

app/searches/measures/search_filters/conditions.rb
app/searches/measures/search_filters/duties.rb

Selecting Conditions are not unspecified or specified breaks search.
[TRELLO STORY](https://trello.com/c/LlkiDd09/377-dit-selecting-conditions-are-not-unspecified-or-specified-breaks-search)

[FIND MEASURES] Fix 'Conditions' filters

---

app/assets/javascripts/components/find-measures.js
app/searches/measures/search_filters/additional_code.rb
spec/support/shared_contexts/searches/measures/is_or_is_not_context.rb
spec/unit/searches/measures/additional_code_filter_spec.rb

Add 'is not specified' and 'is not unspecified' to additional codes search options
[TRELLO STORY](https://trello.com/c/OzFhKj0F/376-dit-add-is-not-specified-and-is-not-unspecified-to-additional-codes-search-options)

[FIND MEASURES] add new options for 'Additional code' filter

---

app/assets/javascripts/components/find-measures.js
app/controllers/measures/measures_controller.rb
app/helpers/measures_helper.rb
app/searches/measures/search.rb
app/searches/measures/search_filters/additional_code.rb
app/searches/measures/search_filters/conditions.rb
app/searches/measures/search_filters/duties.rb
app/searches/measures/search_filters/find_measures_collection.rb
app/searches/measures/search_filters/footnotes.rb
app/searches/measures/search_filters/measure_sid.rb
app/views/measures/measures/_search_form.html.erb
app/views/measures/measures/search_form_parts/_measure_sid_filter.html.erb
app/views/regulations/search/_results.html.slim
config/routes.rb
spec/support/shared_contexts/searches/measures/is_or_is_not_context.rb
spec/unit/searches/measures/additional_code_filter_spec.rb
spec/unit/searches/measures/measure_sid_filter_spec.rb

**1) The searching link on regulations listing does not pre fill the measure search with the regulation id**
[TRELLO CARD](https://trello.com/c/2s6f7Ipj/341-dit-the-searching-link-on-regulations-listing-does-not-pre-fill-the-measure-search-with-the-regulation-id-1)
**2) Selecting Footnotes are not unspecified or specified breaks search**
[TRELLO CARD](https://trello.com/c/6IMJLeIg/378-dit-selecting-footnotes-are-not-unspecified-or-specified-breaks-search)
**3) Selecting Conditions are not unspecified or specified breaks search**
[TRELLO CARD](https://trello.com/c/LlkiDd09/377-dit-selecting-conditions-are-not-unspecified-or-specified-breaks-search)
**4) Add ‘is not specified’ and ‘is not unspecified’ to additional codes search options**
[TRELLO …

[FIND MEASURES] Bugfixes + New features

---

app/assets/javascripts/components/measure_form.js
app/assets/javascripts/vendors/selectize.js
app/assets/javascripts/vue_components/custom-select.js
app/assets/javascripts/vue_components/date-select.js
app/assets/stylesheets/components/find-measures.scss
app/assets/stylesheets/components/forms.scss
app/assets/stylesheets/components/measure-components.scss
app/assets/stylesheets/components/measure-condition-component.scss
app/assets/stylesheets/components/measure-condition.scss
app/assets/stylesheets/components/measure-origin.scss
app/assets/stylesheets/components/remove-row.scss
app/assets/stylesheets/components/select.scss
app/assets/stylesheets/simple-grid.scss
app/views/measures/measures/_search_form.html.erb
app/views/shared/vue_templates/_condition.html.slim
app/views/shared/vue_templates/_date_select.html.slim
app/views/shared/vue_templates/_measure_component.html.slim
app/views/shared/vue_templates/_measure_origin.html.slim
app/views/shared/vue_templates/_selectize.html.slim
app/views/workbaskets/create_measures/steps/duties_conditions_footnotes/_duty_expression.html.slim
app/views/workbaskets/create_measures/steps/main/_start_end_dates.html.slim
app/views/workbaskets/create_measures/steps/main/_workbasket_name.html.slim
app/views/workbaskets/shared/steps/duties_conditions_footnotes/_conditions.html.slim
app/views/workbaskets/shared/steps/main/_additional_codes.html.slim
app/views/workbaskets/shared/steps/main/_commodity_codes_exceptions.html.slim
app/views/workbaskets/shared/steps/main/_geographical_area.html.slim
app/views/workbaskets/shared/steps/main/_reduction_indicator.html.slim
app/views/workbaskets/shared/steps/main/_regulation.html.slim

This PR does the following:
- Implements re-population of fields in create measures form, for steps 1 and 2
- Changes datepickers for 3-select components as requested by Jon in a meeting
- Fixes some typos and removes some unnecessary line breaks in form hints
- Improves styling of conditions, duty expressions
- Fixes ordering and styling of measure origins
- Puts form hints and labels on top of every field on conditions in step 2, due to the fact that it is very rare for both conditions to have the same sequence of fields
- Reduction indicator, reduced size and allowed only one character
Couple screenshots from work done:

Create measures prepopulation

---

app/assets/stylesheets/components/tables.scss
app/views/shared/vue_templates/_measures_grid.html.erb

instead of removing them from the grid
https://trello.com/c/zgjMO6Mg/355-dit-deleting-an-item-should-keep-it-there-and-strikethrough-the-text

strikethrough deleted measures

---

app/assets/javascripts/vue_components/custom-select.js
app/assets/javascripts/vue_components/measure-origin.js
app/views/shared/vue_templates/_measure_origin.html.slim

https://trello.com/c/mdeaxnRH/358-dit-create-measures-form-and-change-origin-popup-which-origin-will-the-measures-apply-to-block-should-not-allow-to-exclude-same

do not allow user to exclude a region twice

---

app/models/measure.rb
app/searches/measures/search_filters/find_measures_collection.rb
app/tasks/measures/reindex_searchable_data.rb
app/workers/searchable_data_reindex_worker.rb
config/sidekiq.yml

For measures we are using separated JSONB field.
**Example:**
```
{"footnotes"=>[{"footnote_id"=>"136", "footnote_type_id"=>"CD"}, {"footnote_id"=>"001", "footnote_type_id"=>"EU"}],
"additional_code"=>"2550",
"footnotes_count"=>2,
"regulation_code"=>"R0316/18",
"duty_expressions"=>[{"duty_amount"=>"0.0", "duty_expression_id"=>"01", "monetary_unit_code"=>"EUR", "measurement_unit_code"=>"TNE"}],
"measure_conditions"=>"_B_",
"duty_expressions_count"=>1,
"measure_conditions_count"=>1}
```
Currently, we are setting it on add / update measure via `set_searchable_data!` callback.
But, there is another case which is not handled by current logic - 'time travel' feature (validity periods - start / end dates).
**For example:**
Today measure having footnotes which are having `validity_end_date` …

[Measures] re-index of searchable data need to be regular

---

app/searches/measures/search_filters/date_universal.rb
spec/unit/searches/measures/valid_to_filter_spec.rb

Search: end date filters for before/after should also include undefined
So you can search for measures in the future and ones without an end date at the same time.
```
end date before X and nil
end date after X and nil 
```
[TRELLO CARD](https://trello.com/c/ksibeV56/372-dit-search-end-date-filters-for-before-after-should-also-include-undefined)

[FIND MEASURES] End date filter: logic improvements

---

app/models/db/rollback_process.rb
app/models/workbaskets/workbasket.rb

Previously we got the issue reported by sentry:
```
undefined method `manual_add=' for #<Workbaskets::Workbasket:0x00007f95ae9b5ac8>
```
This PR fixes that.
[SENTRY ISSUE](https://sentry.io/bit-zesty-client-apps/management/issues/648363976/?referrer=slack)
[TRELLO CARD](https://trello.com/c/gKHXVPgX/412-dit-rollbacks-functionality-issue-nomethoderror-undefined-method-manualadd-for-workbasket)

[ROLLBACKS] updated to work with workbaskets

---

app/models/measure_component.rb
app/models/measure_condition.rb
app/models/measure_condition_component.rb
db/migrate/20180820092723_add_internal_fields_to_duty_expressions.rb
db/structure.sql

Standart DutyExpressions are living in `MeasureComponent` DB model
And DutyExpressions which belongs to Conditions are living in `MeasureConditionComponent` DB model
Conditions are living in `MeasureCondition`  DB model
So we are adding following internal columns:
`MeasureComponent` <- `original_duty_expression_id`
`MeasureConditionComponent` <- `original_duty_expression_id`
`MeasureCondition` <- `original_measure_condition_code`
They would be used as internal triggers for UI building and on saving mechanism.
[TRELLO CARD](https://trello.com/c/l1ou2EW6/406-dit-new-complexity-for-the-conditions-mechanic-in-create-measures-etc-10)

[NEW CONDITIONS MECHANIC] added internal columns for related database tables

---

app/searches/measures/search_filters/conditions.rb
app/searches/measures/search_filters/duties.rb
app/searches/measures/search_filters/footnotes.rb
app/searches/measures/search_filters/origin_exclusions.rb
lib/measures/refresh_cache.rb

**1) [SEARCH IN MEASURES] fix for collection search filters**
[SENTRY ISSUE](https://sentry.io/bit-zesty-client-apps/management/issues/634019078)
Fix applying to:
- footnotes
- conditions
- duties
- origin exclusions
[TRELLO CARD](https://trello.com/c/HJnvX9WL/407-errorwere-sorry-but-something-went-wrong-3)
**2) [CREATE MEASURES] fixed issue with wrong geographical areas list**
So issue was happened when we are selecting:
```
Origin - XD-Mayotte
```
Because `XD-Mayotte` is not longer actual geographical area.
DB record for `XD-Mayotte`:
```
:geographical_area_sid=>329,
:parent_geographical_area_group_sid=>nil,
:validity_start_date=>"1984-01-01T00:00:00.000Z",
:validity_end_date=>"1994-12-31T00:00:00.000Z",
:geographical_code=>"2",
:geographical_area_id=>"XD",
}>
```
So …

[SHOW STOPPER BUGS] Fixes

---

app/assets/javascripts/vue_components/change-footnotes-popup.js
app/assets/stylesheets/components/tables.scss

addresses
- a. When you try to bulk edit Footnotes, there are missing lines on the highlights
- e. After you remove all the footnotes, select Edit Footnotes again,then select any footnotes, the "Update Selected Measures" seems to be disabled permanently.
https://trello.com/c/XOvqXITQ/314-dit-bulk-edit-popups-footnotes-5

fixes on change footnotes popup

---

app/interactors/workbasket_interactions/settings_saver_base.rb
app/services/workbasket_services/quota_savers/order_number.rb
app/value_objects/workbasket_value_objects/attributes_parser_base.rb

ME10 conformance rule was accusing order number as `nil`.
From the UI perspective it was being set, it was even being saved in the JSON payload.
However, there was a issue of parameter name when normalising params for measure creation, leaving order number blank, and thus not passing validation.
I happen to have stumbled into another issue regarding creation of measure origin exclusions, when trying to create an Erga Omnes measure with AF as exclusion.
Fixed saving there as well.

Fixing issue on saver that was blocking both create measures and create quotas from going past step 2

---

app/assets/javascripts/components/conditions-parser.js
app/assets/javascripts/components/duty-expressions-parser.js
app/assets/javascripts/components/measure_form.js
app/assets/javascripts/components/workbaskets/save-actions.js.coffee
app/assets/javascripts/components/workbaskets/validation_errors_handler.js.coffee
app/assets/javascripts/vue_components/components-coordinator.js
app/assets/javascripts/vue_components/conditions-coordinator.js
app/assets/javascripts/vue_components/custom-select.js
app/assets/javascripts/vue_components/measure-components.js
app/assets/javascripts/vue_components/measure-condition.js
app/assets/javascripts/vue_components/opening-balances-manager.js
app/assets/stylesheets/components/forms.scss
app/assets/stylesheets/components/measure-components.scss
app/assets/stylesheets/components/measure-condition-component.scss
app/assets/stylesheets/components/measure-condition.scss
app/assets/stylesheets/components/select.scss
app/assets/stylesheets/simple-grid.scss
app/value_objects/workbasket_value_objects/attributes_parser_base.rb
app/views/shared/vue_templates/_condition.html.slim
app/views/shared/vue_templates/_measure_component.html.slim
app/views/shared/vue_templates/_measure_condition_component.html.slim
app/views/workbaskets/create_quota/steps/main/_licensed_block.html.slim
db/structure.sql

This PR implements new conditions & duty expressions mechanics.
- There were design changes, making the selects less wide
- Some conditions were split
- "Holes" in UI for measure condition components now propagate across conditions
- Fixed save buttons
- Fixed double saving
- FIxed issue of VueJS reusing custom-select component, making selections from, for example, certificate types appear for measurement units
Thanks @rusllonrails for the extra columns on tables to make this possible.
PS: one thing noted in card, but worth repeating here, is that for conditions M1 and M2, for new records it will be possible to distinguish them, but not when editing old measures.

New conditions & duty expressions mechanics

---

app/views/measures/bulks/edit.html.slim

Now there are 2 variables available:
`window.all_settings`
Example of output:
```
{title: "TEST BRO", reason: "TEST REASONS", start_date: "30/09/2018", regulation_id: "C1402160", regulation_role: "1"}
```
and `window.current_step_settings`, which is alias for `window.all_settings`.
[TRELLO CARD](https://trello.com/c/qzcmmsQ0/484-dit-bulk-edit-of-measures-update-system-to-work-with-updated-ui-new-step-with-extra-data-for-workbasket)

[BULK EDIT OF MEASURES] added JS variables for data from first step form

---

app/assets/stylesheets/components/layout.scss
app/views/workbaskets/create_measures/_form.html.slim
app/views/workbaskets/create_quota/_form.html.slim
app/views/workbaskets/shared/_errors_container.html.slim

Previously removed in a refactoring, but didn't realize error container was being used by "save progress" button, and a custom block for Continue.

Adding errors back on when pressing save progress

---

app/assets/javascripts/components/bulk-edit-measures.js
app/assets/javascripts/vue_components/change-validity-period-popup.js
app/assets/javascripts/vue_components/measures-grid.js
app/views/shared/vue_templates/_change_validity_period.html.erb

This PR implements a couple fixes related to bulk edit page:
- The interaction of checkboxes selection and "select all" checkbox is now fixed
- Fixed edge case of daylight savings or timezone when parsing dates
- Properly validating regulation on validity period popup

Bulk edit fixes

---

app/models/measure_component.rb
app/searches/measures/search_filters/date_universal.rb
app/searches/measures/search_filters/measure_sid.rb
app/views/measures/measures/search_form_parts/_measure_sid_filter.html.erb
spec/unit/searches/measures/measure_sid_filter_spec.rb
spec/unit/searches/measures/valid_to_filter_spec.rb

fix error when duty_expression is not present for measure_component.
fixed explicit end_date in measure search.

Search measure error fixes

---

lib/trade_tariff_backend/validations/validity_date_span_validation.rb

added a check if validity start date is not present in ValidityDateSpanValidation.

fixed crash if validity start date is not present.

---

app/assets/javascripts/components/find-measures.js
app/views/measures/measures/_search_form.html.erb

fix the crash if footnote type was select and then deleted.
added an empty footnote line for existing search params.
disable footnote id field in case footnote type is not specified.

Search with footnotes fixes

---

app/assets/javascripts/application.js
app/assets/javascripts/components/measure_form.js
app/assets/javascripts/components/quota-form.js
app/assets/javascripts/vue_components/date-select.js
app/assets/javascripts/vue_components/measure-origin.js
app/assets/javascripts/vue_components/opening-balances-manager.js
app/assets/javascripts/vue_components/parent-quota-opening-balances.js
app/assets/javascripts/vue_components/quota-section.js
app/assets/javascripts/vue_components/quota-sections-manager.js
app/assets/javascripts/vue_components/sub-origin.js
app/assets/javascripts/vue_components/sub-quota-definitions.js
app/assets/stylesheets/components/create-measures.scss
app/assets/stylesheets/components/forms.scss
app/assets/stylesheets/components/measure-origin.scss
app/assets/stylesheets/components/opening-balance.scss
app/assets/stylesheets/components/parent-quota.scss
app/assets/stylesheets/components/sub-quota-definition.scss
app/value_objects/workbasket_value_objects/create_quota/step_pointer.rb
app/views/shared/vue_templates/_measure_origin.html.slim
app/views/shared/vue_templates/_opening_balances_manager.html.erb
app/views/shared/vue_templates/_quota_section.html.erb
app/views/workbaskets/create_measures/steps/_main.html.slim
app/views/workbaskets/create_quota/_form.html.slim
app/views/workbaskets/create_quota/steps/_conditions_footnotes.html.slim
app/views/workbaskets/create_quota/steps/_main.html.slim
app/views/workbaskets/create_quota/steps/duties_conditions_footnotes/_sub_quotas.html.erb
app/views/workbaskets/create_quota/steps/main/_licensed_block.html.slim
app/views/workbaskets/shared/steps/main/_geographical_area.html.slim

This PR achieves the following:
- Updates origins component to accept multiple countries/territories and not repeat them
- Hide all duty related fields from quota periods if Quota is licensed
- Implements for for quota associations:
- sub quotas
- parent quotas
- Implements correct conditionals for custom quota periods, limiting them to 1 year
Besides, this PR starts to refactor quota form out of measure form, but the changes would become too big for one PR.

UI changes to quota flow

---

app/assets/javascripts/vue_components/custom-select.js

Issue was happening when user searched for an option, selects an option,
then deselects option, and when opening the select again, the user only
sees the results for the previous search.
This commits forces a refresh when a option is deselected.

Refetching options when selection is cleared

---

app/assets/javascripts/vue_components/date-select.js
app/assets/javascripts/vue_components/popup.js

There was an issue when popups open, Vue would render the datepickers
before the popups rendered fully, causing a misalignment.
This PR triggers an event after the popups fully render, so that
datepickers have a chance of repositioning themselves.

Repositioning datepickers when popups open

---

app/assets/javascripts/components/bulk-edit-measures.js

Removing assumption to clear end date when bulk editing measures.

Leave end date as is when bulk editing measures

---

app/assets/stylesheets/components/forms.scss
app/views/shared/vue_templates/_change_commodity_codes.html.erb

Fields were misaligned horizontally.
Changed structure so they align

Fixing layout of change commodity codes popup

---

config/initializers/rack_timeout.rb

This setting was throwing an error while loading Rails console

Remove Rack::Timeout related settings as we have removed this gem.

---

app/assets/javascripts/vue_components/button-dropdown.js
app/views/measures/bulks/edit.html.slim

Behaviour was actually as per standard.
Pressing Enter on the keyboard while on an input should trigger form submission.
Bulk edit screen was unnecessarily a form element, thus causing this issue.

Fixing spooky dropdown opening
